### PR TITLE
Fix/wextra

### PR DESCRIPTION
**Pull request by firesurfer**
This PR activates -Wextra. 

I didnt fix the compiler errors yet on purpose because they need some discussion:

e.g.

`EthercatSlaveBase.hpp:230:90: error: unused parameter ‘completeAccess’ [-Werror=unused-parameter]
  230 |   virtual bool sendSdoWriteInt8(const uint16_t index, const uint8_t subindex, const bool completeAccess, const int8_t value) {
`

This is in the end due to `completeAccess` not being passed to the sendSdoWrite function
`
  virtual bool sendSdoWriteInt8(const uint16_t index, const uint8_t subindex, const bool completeAccess, const int8_t value) {
    return sendSdoWrite(index, subindex, false, value);
  }
`
@JohannesPankert or @jungerj  does anyone of you have some insight why this is not the case?

### CODE REVIEW

**Review by tomlankhorst — APPROVED** [review]
-Wextra is good. Corresponding warnings can be discussed separately. 

Regarding the one mentioned by @firesurfer, the current state is confusing indeed and the parameter should either be made effective or removed.

**Comment by firesurfer** [comment]
Due to -Werror the extra warnings need to be addresses before merging

**Comment by JohannesPankert** [comment]
I am not a huge fan of using werror on CI. Especially if you activate wextra and wpedantic. This essentially creates a dependency on the compiler version you use.

**Comment by firesurfer** [comment]
I think on such a base package which isn't touched to much -Werror actually makes sense. Also the warnings can be fixed rather easily

**Comment by tomlankhorst** [comment]
The compiler version follows from the Ubuntu distribution though and since we typically support one or two distros at the same time, that shouldn't be too troublesome.

**Pull request closed without merging**
